### ISSUE TITLE
Too aggressive Intention - suggest to make it callable via Find action

### ISSUE THREAD

**Issue by jakubboucek** [jiripudil/intellij-nette-factory-generator#5]
_Czech only_

Plugin používám teprve 2 dny, už mi ušetřil při refaktoringu hromadu času, díky. Nicméně když jsem jej přestal intenzivně potřebovat, stává se poněkud vlezlý, protože vyhazuje Intention notification (žlutou žárovku `Show Intention actions`, <kbd>Alt</kbd> + <kbd>Enter</kbd>) v **každé** PHP třídě na **každém** řádku.

Zkusil jsem pluginu deaktivovat v `Preferences → Editor → Intentions → Nette`, to problém vyřešilo, bohužel se tím ale stala funce nedostupná, protože ji zřejmě nelze volat jinak, ani přes `Find action…`, <kbd>Shift</kbd> + <kbd>Cmd</kbd> + <kbd>A</kbd>, leda bych se nějak blbě díval (je tam možnost za/vypínat Intentions a nastavení).

![180129-weexh](https://user-images.githubusercontent.com/1657322/35494760-17f063b6-04bd-11e8-81ee-4944613cd968.png)

**Comment by jiripudil** [comment]
Ahoj,

jsem rád, že plugin slouží :)

Za report děkuji, zkusím se podívat, jestli ten intention nedokážu pro začátek přesunout jen nad název třídy a později případně přijít s něčím ještě trochu inteligentnějším.
