### ISSUE TITLE
Config line?

### ISSUE THREAD

**Issue by JKoty** [jiripudil/intellij-nette-factory-generator#6]
_Czech only_
Ahoj,
super věc. 👍 
Říkám si, že by bylo boží, kdyby šlo někde mít .neon, do kterého by to ten interface rovnou zaregistrovalo. Stačil by speciální soubor jenom na to, kam by plugin přidal řádek (a pak bych si to třeba importoval z jiného configu).

Je to hloupost, nebo mám zkusit vymyslet úpravu?

**Comment by jiripudil** [comment]
Ahoj, myšlenka je hezká, ale osobně se mi to moc přidávat nechce, protože odbýt to triviálním řešením, jak navrhuješ, by znamenalo vnucovat uživatelům konkrétní způsob psaní/strukturování konfigurace, což by plugin podle mě dělat neměl – kód se přece nemůže přizpůsobovat nástrojům, ale naopak –, a napsat dostatečně spolehlivé obecné řešení by bylo až příliš netriviální.

Ale možná jako opt-in a s dostatečným varováním by to triviální řešení mohlo fungovat, takže jestli se do toho chceš pustit, bránit se tomu nijak kategoricky nebudu.

**Comment by JKoty** [comment]
Jak to tak řeším, tak by celkově bylo logičtější mít na to úplně jiný generátor s vlastním nastavením, který by se následně volal a tak by to bylo opt-in.
