### ISSUE TITLE
Generate (optionally?) "declare(strict_types = 1);"

### ISSUE THREAD

**Issue by khorsky** [jiripudil/intellij-nette-factory-generator#7]
Would it be possible to add "declare(strict_types = 1);" to the beginning of the template?

I guess not everyone would need that, but I usually forget to edit it.

Anyway - thanks for a big time saver...

**Comment by jiripudil** [comment]
Hello, as far as I remember, this plugin should be using the `PHP File` file template, so any changes to it are entirely at your discretion.

**Comment by khorsky** [comment]
Oh, thanks for that information, you're right. I was looking for plugin template and that didn't come to my mind.

Closing.
